from . import battery_service
from . import product_model_category
from . import product_model
from . import product_template
from . import rom_size
from . import sim_lock
from . import use_limit
from . import telecom_carrier
from . import product_grade
from . import qa_state
